@Library('ci-jenkins-shared-libraries@main') _
def cipipeline = new opstree.ci.templates.java_ci.java_ci()

node {
    cipipeline.call([

        // WORKSPACE MANAGEMENT
        clean_workspace: true,

        // VCS MANAGEMENT
        repo_https_url           : "https://bitbucket.org/montra_app/apigateway.git",
        repo_ssh_url             : "git@bitbucket.org:montra_app/apigateway.git",
        repo_branch              : params.BRANCH ?: "main",
        repo_url_type            : "http",
        jenkins_git_creds_id     : "BITBUCKET_CREDENTIALS",
        source_code_path         : "",

        // DEPENDENCY SCANNING
        dependency_check         : 'true',
        dependency_scan_tool     : 'owasp',
        owasp_project_name       : 'apigateway',
        owasp_report_publish     : 'true',
        owasp_report_format      : 'html',
        fail_job_if_dependency_returned_exception: 'false',
        nvd_api_key_creds_id     : 'NVD_API_KEY',

        // CREDS SCANNING (GITLEAKS)
        gitleaks_check                  : true,
        fail_job_if_leak_detected       : false,
        gitleaks_scan_mode              : 'full',
        gitleaks_report_jenkins_publish : true,

        // BUILD ARTIFACT
        perform_code_build         : true,
        build_tool                 : 'gradle',
        gradle_command             : 'clean build -x jar',
        gradle_build_file_location : '.',
        java_version               : '21',
        codeartifact_dependency    : false,
        codeartifact_domain        : '',
        codeartifact_owner         : '',
        pom_location               : '',

        // UNIT TESTING
        unit_testing_check              : 'true',
        fail_job_if_unit_issue_detected : 'false',
        unit_test_reports_path          : '**/build/test-results/test/*.xml',

        // STATIC CODE ANALYSIS
        static_code_analysis_check              : true,
        codebase_to_scan_directory              : '.',
        sonar_project_key                       : 'apigateway',
        sonar_project_name                      : 'apigateway',
        sonar_sources                           : 'src/main/java',
        sonar_extra_args                        : '-Dsonar.java.binaries=build/classes/java/main',
        fail_job_if_analysis_returned_exception : 'false',
        jenkins_sonarqube_token_creds_id        : 'SONARQUBE_TOKEN',

        // BUILD DOCKERFILE
        perform_build_dockerfile : true,
        dockerfile_location      : '/Dockerfile',
        dockerfile_context       : '',
        image_name               : 'apigateway',
        image_tag                : 'latest',

        // IMAGE SCANNING (TRIVY)
        image_scanning_check         : true,
        scan_severity                : 'HIGH,CRITICAL',
        image_scanning_report_publish: 'true',

        // IMAGE SIZE VALIDATOR
        image_size_validator_check : true,
        max_allowed_image_size     : '500',
        fail_job_if_validation_fail: 'false',

        // PUBLISH ARTIFACT
        artifact_publish_check   : true,
        artifact_destination_type: 'gcr',
        docker_image_name        : 'apigateway',
        gcp_project_id           : 'montra-490412',
        gcr_hostname             : 'asia-south2-docker.pkg.dev',
        gcr_repository           : 'dev-app-images',

        // DEPLOYMENT
        enable_trigger_cd_pipeline: true,
        trigger_cd_pipeline_path  : "CD/apigateway",
        image_tag_build_param     : 'image_tag',

        // NOTIFICATION
        notification_enabled: false
    ])
}
