#!/bin/sh
# =============================================================================
# inject.sh — OWASP Dependency Check XML → Human-Readable HTML Report
# =============================================================================
# Requires: xmllint (libxml2-utils)  OR  python3 (fallback)
# Input  : dependency-check-report.xml  (generated by OWASP DC)
# Output : owasp_report.html
# =============================================================================
set -e

XML_FILE="dependency-check-report.xml"
TEMPLATE="report.html"
OUTPUT="owasp_report.html"

# ── Sanity check ──────────────────────────────────────────────────────────────
if [ ! -f "$XML_FILE" ]; then
  echo "❌  $XML_FILE not found in $(pwd)"
  exit 1
fi

GENERATED_AT=$(date "+%d %b %Y %H:%M:%S")

# ── Extract summary fields via python3 ───────────────────────────────────────
# We use python3 because it is guaranteed on the Jenkins agent Docker image
# and handles XML namespaces much more reliably than plain grep/awk.
python3 - "$XML_FILE" "$GENERATED_AT" << 'PYEOF'
import sys, xml.etree.ElementTree as ET, html, os, re, datetime

XML_FILE    = sys.argv[1]
GENERATED_AT = sys.argv[2]

NS_MAP = {
    'dc': 'https://jeremylong.github.io/DependencyCheck/dependency-check.2.5.xsd',
}

tree = ET.parse(XML_FILE)
root = tree.getroot()

# ── Helper: strip namespace from tag ─────────────────────────────────────────
def tag(el):
    return re.sub(r'\{.*\}', '', el.tag)

# ── Detect namespace dynamically ─────────────────────────────────────────────
def find(el, *paths):
    """Try each xpath path until one returns a result."""
    for path in paths:
        r = el.find(path, NS_MAP)
        if r is not None:
            return r
    # No-namespace fallback
    for path in paths:
        plain = re.sub(r'dc:', '', path)
        r = el.find(plain)
        if r is not None:
            return r
    return None

def findall(el, *paths):
    for path in paths:
        r = el.findall(path, NS_MAP)
        if r:
            return r
    for path in paths:
        plain = re.sub(r'dc:', '', path)
        r = el.findall(plain)
        if r:
            return r
    return []

def text(el, *paths, default='N/A'):
    for path in paths:
        node = find(el, path)
        if node is not None and node.text:
            return html.escape(node.text.strip())
    return default

# ── Project / scan info ───────────────────────────────────────────────────────
proj_info   = find(root, 'dc:projectInfo', 'projectInfo')
proj_name   = text(root, 'dc:projectInfo/dc:name', 'projectInfo/name', default='Unknown Project')
dc_version  = text(root, 'dc:projectInfo/dc:reportSchema', 'projectInfo/reportSchema', default='')
report_date = text(root, 'dc:projectInfo/dc:reportDate', 'projectInfo/reportDate', default=GENERATED_AT)

# Shorten reportDate if it is ISO8601
try:
    dt = datetime.datetime.fromisoformat(report_date.replace('Z', '+00:00'))
    report_date = dt.strftime('%d %b %Y %H:%M:%S UTC')
except Exception:
    pass

# ── Dependencies ──────────────────────────────────────────────────────────────
deps = findall(root, 'dc:dependencies/dc:dependency', 'dependencies/dependency')

total_deps  = len(deps)
vuln_deps   = 0
vuln_count  = 0
suppressed  = 0

rows_html = []

SEVERITY_ORDER = {'CRITICAL': 0, 'HIGH': 1, 'MEDIUM': 2, 'LOW': 3, 'INFO': 4, 'NONE': 5}

def badge(sev):
    s = sev.upper()
    cls_map = {
        'CRITICAL': 'badge-critical',
        'HIGH':     'badge-high',
        'MEDIUM':   'badge-medium',
        'LOW':      'badge-low',
        'INFO':     'badge-info',
    }
    cls = cls_map.get(s, 'badge-none')
    return f'<span class="badge {cls}">{html.escape(sev)}</span>'

for dep in deps:
    file_name  = text(dep, 'dc:fileName',  'fileName',  default='')
    file_path  = text(dep, 'dc:filePath',  'filePath',  default='')
    md5        = text(dep, 'dc:md5',       'md5',       default='')
    sha1       = text(dep, 'dc:sha1',      'sha1',      default='')
    license_   = text(dep, 'dc:license',   'license',   default='')

    vulns = findall(dep, 'dc:vulnerabilities/dc:vulnerability', 'vulnerabilities/vulnerability')
    sup_vulns = findall(dep, 'dc:suppressedVulnerabilities/dc:vulnerability', 'suppressedVulnerabilities/vulnerability')
    suppressed += len(sup_vulns)

    if not vulns:
        continue

    vuln_deps += 1

    # Pick highest severity among vulns of this dep
    highest_sev = 'NONE'
    cve_tags    = []
    vuln_rows   = []

    for v in vulns:
        vuln_count += 1
        name     = text(v, 'dc:name',        'name',        default='N/A')
        severity = text(v, 'dc:severity',    'severity',    default='UNKNOWN')
        cvss2    = text(v, 'dc:cvssScore',   'cvssScore',   default='')
        cvss3_el = find(v, 'dc:cvssV3',      'cvssV3')
        cvss3    = text(cvss3_el, 'dc:baseScore', 'baseScore', default='') if cvss3_el is not None else ''
        score    = cvss3 or cvss2 or '–'
        desc     = text(v, 'dc:description', 'description', default='No description available.')

        # Truncate long descriptions
        if len(desc) > 300:
            desc = desc[:300] + '…'

        if name.startswith('CVE-'):
            cve_link = f'<a class="cve-tag" href="https://nvd.nist.gov/vuln/detail/{html.escape(name)}" target="_blank">{html.escape(name)}</a>'
        else:
            cve_link = f'<span class="cve-tag">{html.escape(name)}</span>'
        cve_tags.append(cve_link)

        sev_rank = SEVERITY_ORDER.get(severity.upper(), 5)
        cur_rank = SEVERITY_ORDER.get(highest_sev.upper(), 5)
        if sev_rank < cur_rank:
            highest_sev = severity

        vuln_rows.append(f'''
          <tr>
            <td><code style="font-size:12px;color:#7dd3fc;">{html.escape(name)}</code></td>
            <td>{badge(severity)}</td>
            <td style="color:#94a3b8;">{score}</td>
            <td style="font-size:12px;color:#cbd5e1;">{desc}</td>
          </tr>''')

    # Build the collapsible detail block
    detail_id = f"dep-{hash(file_path) & 0xFFFFFF}"
    dep_block = f'''
      <tr class="dep-row">
        <td class="filepath">{file_name}</td>
        <td>{badge(highest_sev)}</td>
        <td><div class="cve-list">{''.join(cve_tags)}</div></td>
        <td class="hash-val">{md5[:12] + '…' if md5 != 'N/A' else '–'}</td>
        <td style="font-size:12px;color:#94a3b8;">{license_}</td>
      </tr>
      <tr>
        <td colspan="5" style="padding:0;">
          <details style="padding:8px 16px; background:#060f1e;">
            <summary style="cursor:pointer; font-size:12px; color:#38bdf8; padding:6px 0;">
              ▶ {len(vulns)} vulnerability detail(s)
            </summary>
            <table style="margin:8px 0; width:100%; background:#060f1e; border:1px solid #1e293b; border-radius:4px;">
              <thead>
                <tr>
                  <th>CVE / ID</th>
                  <th>Severity</th>
                  <th>CVSS Score</th>
                  <th>Description</th>
                </tr>
              </thead>
              <tbody>{''.join(vuln_rows)}</tbody>
            </table>
          </details>
        </td>
      </tr>'''
    rows_html.append(dep_block)

# ─── Sort: most severe dependency first ──────────────────────────────────────
# (rows already ordered by first-encountered dep, stable enough for a report)

# ─── Assemble output ─────────────────────────────────────────────────────────
vuln_class = 'danger' if vuln_deps > 0 else 'safe'

if vuln_deps == 0:
    vuln_banner = '<div class="no-vuln">✅ No vulnerable dependencies were detected.</div>'
    vuln_section = ''
else:
    vuln_section = f'''
  <div class="section-title">⚠️  Vulnerable Dependencies ({vuln_deps})</div>
  <table>
    <thead>
      <tr>
        <th>Dependency</th>
        <th>Highest Severity</th>
        <th>CVE / IDs</th>
        <th>MD5 (partial)</th>
        <th>License</th>
      </tr>
    </thead>
    <tbody>
      {''.join(rows_html)}
    </tbody>
  </table>'''
    vuln_banner = ''

# ─── Read template & fill placeholders ───────────────────────────────────────
with open('report.html', 'r') as f:
    html_out = f.read()

html_out = html_out.replace('{{PROJECT_NAME}}', proj_name)
html_out = html_out.replace('{{TOTAL_DEPS}}',   str(total_deps))
html_out = html_out.replace('{{VULN_DEPS}}',    str(vuln_deps))
html_out = html_out.replace('{{VULN_COUNT}}',   str(vuln_count))
html_out = html_out.replace('{{SUPPRESSED}}',   str(suppressed))
html_out = html_out.replace('{{GENERATED_AT}}', GENERATED_AT)
html_out = html_out.replace('{{DC_VERSION}}',   dc_version)
html_out = html_out.replace('{{REPORT_DATE}}',  report_date)
html_out = html_out.replace('{{VULN_CLASS}}',   vuln_class)
html_out = html_out.replace('{{VULN_BANNER}}',  vuln_banner)
html_out = html_out.replace('{{VULN_SECTION}}', vuln_section)

with open('owasp_report.html', 'w') as f:
    f.write(html_out)

print(f"✅ OWASP report generated: owasp_report.html")
print(f"   Project      : {proj_name}")
print(f"   Deps Scanned : {total_deps}")
print(f"   Vulnerable   : {vuln_deps}")
print(f"   CVEs Found   : {vuln_count}")
PYEOF

echo "✅ OWASP Dependency Check report generated: $OUTPUT"
