#!/bin/sh
# =============================================================================
# inject.sh — OWASP Dependency Check XML → Human-Readable HTML Report
# =============================================================================
# Requires: python3
# Input  : dependency-check-report.xml  (generated by OWASP DC)
# Output : owasp_report.html
# =============================================================================
set -e

XML_FILE="dependency-check-report.xml"
OUTPUT="owasp_report.html"

# ── Sanity check ──────────────────────────────────────────────────────────────
if [ ! -f "$XML_FILE" ]; then
  echo "❌  $XML_FILE not found in $(pwd)"
  exit 1
fi

GENERATED_AT=$(date "+%d %b %Y %H:%M:%S")

# ── Parse XML and generate HTML report via python3 ───────────────────────────
# KEY FIX: Strip ALL namespace prefixes from the XML before parsing.
# dependency-check changes its XSD namespace across versions (1.3, 2.5, etc.)
# so hardcoding any namespace causes 0-result lookups on newer releases.
python3 - "$XML_FILE" "$GENERATED_AT" << 'PYEOF'
import sys, re, html as html_lib, datetime
import xml.etree.ElementTree as ET

XML_FILE     = sys.argv[1]
GENERATED_AT = sys.argv[2]

# ── Step 1: Strip ALL namespace declarations + prefixes from raw XML ──────────
# This makes every element accessible by its plain local name, regardless of
# which XSD version the dependency-check release uses.
with open(XML_FILE, 'r', encoding='utf-8', errors='replace') as f:
    raw = f.read()

# Remove xmlns declarations:  xmlns="..."  and  xmlns:xxx="..."
raw = re.sub(r'\s+xmlns(?::\w+)?="[^"]*"', '', raw)
# Remove remaining namespace prefixes on tags: <ns:tag> → <tag>, </ns:tag> → </tag>
raw = re.sub(r'<(/?)[\w.-]+:([\w.-]+)', r'<\1\2', raw)

root = ET.fromstring(raw)

# ── Step 2: Helper functions ──────────────────────────────────────────────────
def find_el(el, path):
    """Simple find using plain (no-namespace) xpath."""
    return el.find(path)

def findall_el(el, path):
    return el.findall(path)

def get_text(el, path, default='N/A'):
    node = find_el(el, path) if el is not None else None
    if node is not None and node.text:
        return html_lib.escape(node.text.strip())
    return default

# ── Step 3: Project / scan info ──────────────────────────────────────────────
proj_name   = get_text(root, 'projectInfo/name',       default='N/A')
dc_version  = get_text(root, 'projectInfo/reportSchema', default='')
report_date = get_text(root, 'projectInfo/reportDate', default=GENERATED_AT)

# Shorten ISO8601 date
try:
    dt = datetime.datetime.fromisoformat(report_date.replace('Z', '+00:00'))
    report_date = dt.strftime('%d %b %Y %H:%M:%S UTC')
except Exception:
    pass

# ── Step 4: Count dependencies ────────────────────────────────────────────────
deps       = findall_el(root, 'dependencies/dependency')
total_deps = len(deps)
vuln_deps  = 0
vuln_count = 0
suppressed = 0

rows_html = []

SEVERITY_ORDER = {'CRITICAL': 0, 'HIGH': 1, 'MEDIUM': 2, 'LOW': 3, 'INFO': 4, 'NONE': 5}

def badge(sev):
    s = (sev or 'NONE').upper()
    cls_map = {
        'CRITICAL': 'badge-critical',
        'HIGH':     'badge-high',
        'MEDIUM':   'badge-medium',
        'LOW':      'badge-low',
        'INFO':     'badge-info',
    }
    cls = cls_map.get(s, 'badge-none')
    return f'<span class="badge {cls}">{html_lib.escape(sev or "NONE")}</span>'

for dep in deps:
    file_name = get_text(dep, 'fileName',  default='')
    file_path = get_text(dep, 'filePath',  default='')
    md5       = get_text(dep, 'md5',       default='')
    license_  = get_text(dep, 'license',   default='')

    vulns     = findall_el(dep, 'vulnerabilities/vulnerability')
    sup_vulns = findall_el(dep, 'suppressedVulnerabilities/vulnerability')
    suppressed += len(sup_vulns)

    if not vulns:
        continue

    vuln_deps += 1
    highest_sev = 'NONE'
    cve_tags    = []
    vuln_rows   = []

    for v in vulns:
        vuln_count += 1
        name     = get_text(v, 'name',        default='N/A')
        severity = get_text(v, 'severity',    default='UNKNOWN')
        cvss2    = get_text(v, 'cvssScore',   default='')

        # cvssV3 block
        cvss3_el = find_el(v, 'cvssV3')
        cvss3    = get_text(cvss3_el, 'baseScore', default='') if cvss3_el is not None else ''
        score    = cvss3 or cvss2 or '–'

        desc     = get_text(v, 'description', default='No description available.')
        if len(desc) > 320:
            desc = desc[:320] + '…'

        if name.startswith('CVE-'):
            cve_link = f'<a class="cve-tag" href="https://nvd.nist.gov/vuln/detail/{html_lib.escape(name)}" target="_blank">{html_lib.escape(name)}</a>'
        else:
            cve_link = f'<span class="cve-tag">{html_lib.escape(name)}</span>'
        cve_tags.append(cve_link)

        sev_rank = SEVERITY_ORDER.get((severity or '').upper(), 5)
        cur_rank = SEVERITY_ORDER.get(highest_sev.upper(), 5)
        if sev_rank < cur_rank:
            highest_sev = severity

        vuln_rows.append(f'''
          <tr>
            <td><code style="font-size:12px;color:#7dd3fc;">{html_lib.escape(name)}</code></td>
            <td>{badge(severity)}</td>
            <td style="color:#94a3b8;">{score}</td>
            <td style="font-size:12px;color:#cbd5e1;">{desc}</td>
          </tr>''')

    md5_display = (md5[:12] + '…') if (md5 and md5 != 'N/A') else '–'
    dep_block = f'''
      <tr class="dep-row">
        <td class="filepath">{file_name}</td>
        <td>{badge(highest_sev)}</td>
        <td><div class="cve-list">{''.join(cve_tags)}</div></td>
        <td class="hash-val">{md5_display}</td>
        <td style="font-size:12px;color:#94a3b8;">{license_}</td>
      </tr>
      <tr>
        <td colspan="5" style="padding:0;">
          <details style="padding:8px 16px; background:#060f1e;">
            <summary style="cursor:pointer; font-size:12px; color:#38bdf8; padding:6px 0;">
              ▶ {len(vulns)} vulnerability detail(s)
            </summary>
            <table style="margin:8px 0; width:100%; background:#060f1e; border:1px solid #1e293b; border-radius:4px;">
              <thead>
                <tr>
                  <th>CVE / ID</th><th>Severity</th><th>CVSS Score</th><th>Description</th>
                </tr>
              </thead>
              <tbody>{''.join(vuln_rows)}</tbody>
            </table>
          </details>
        </td>
      </tr>'''
    rows_html.append(dep_block)

# ── Step 5: Assemble final HTML ───────────────────────────────────────────────
vuln_class = 'danger' if vuln_deps > 0 else 'safe'

if vuln_deps == 0:
    vuln_banner  = '<div class="no-vuln">✅ No vulnerable dependencies were detected.</div>'
    vuln_section = ''
else:
    vuln_section = f'''
  <div class="section-title">⚠️  Vulnerable Dependencies ({vuln_deps})</div>
  <table>
    <thead>
      <tr>
        <th>Dependency</th>
        <th>Highest Severity</th>
        <th>CVE / IDs</th>
        <th>MD5 (partial)</th>
        <th>License</th>
      </tr>
    </thead>
    <tbody>
      {''.join(rows_html)}
    </tbody>
  </table>'''
    vuln_banner = ''

with open('report.html', 'r') as f:
    html_out = f.read()

html_out = html_out.replace('{{PROJECT_NAME}}', proj_name)
html_out = html_out.replace('{{TOTAL_DEPS}}',   str(total_deps))
html_out = html_out.replace('{{VULN_DEPS}}',    str(vuln_deps))
html_out = html_out.replace('{{VULN_COUNT}}',   str(vuln_count))
html_out = html_out.replace('{{SUPPRESSED}}',   str(suppressed))
html_out = html_out.replace('{{GENERATED_AT}}', GENERATED_AT)
html_out = html_out.replace('{{DC_VERSION}}',   dc_version)
html_out = html_out.replace('{{REPORT_DATE}}',  report_date)
html_out = html_out.replace('{{VULN_CLASS}}',   vuln_class)
html_out = html_out.replace('{{VULN_BANNER}}',  vuln_banner)
html_out = html_out.replace('{{VULN_SECTION}}', vuln_section)

with open('owasp_report.html', 'w') as f:
    f.write(html_out)

print(f"✅  OWASP report generated: owasp_report.html")
print(f"    Project      : {proj_name}")
print(f"    Deps Scanned : {total_deps}")
print(f"    Vulnerable   : {vuln_deps}")
print(f"    CVEs Found   : {vuln_count}")
print(f"    Suppressed   : {suppressed}")
PYEOF

echo "✅ OWASP Dependency Check report generated: $OUTPUT"
